version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  redis-insights:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis
