version: '3.3'

services:
  api:
    build: .
    restart: always
    depends_on:
      - redis
    ports:
      - "3000:3000"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

