basePath: /api/v1
definitions:
  api.CellValue:
    properties:
      value:
        type: string
    required:
    - value
    type: object
  api.HTTPError:
    properties:
      message: {}
    type: object
  api.ValueResponse:
    properties:
      cell:
        type: string
      result:
        type: string
      sheet:
        type: string
      value:
        type: string
    required:
    - cell
    - sheet
    type: object
host: localhost:3000
info:
  contact:
    email: iostapovychweb@gmail.com
  description: Educational Excel-like API
  title: ITSUXEL
  version: "1.0"
paths:
  /table/{sheet}:
    get:
      consumes:
      - application/json
      parameters:
      - description: sheet name
        in: path
        name: sheet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/api.ValueResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: returns cell value
  /table/{sheet}/{cell}:
    get:
      consumes:
      - application/json
      parameters:
      - description: sheet name
        in: path
        name: sheet
        required: true
        type: string
      - description: cell address
        in: path
        name: cell
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.ValueResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: returns cell value
    post:
      consumes:
      - application/json
      description: Add a new pet to the store
      parameters:
      - description: sheet name
        in: path
        name: sheet
        required: true
        type: string
      - description: cell address
        in: path
        name: cell
        required: true
        type: string
      - description: Set Cell Value
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/api.CellValue'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HTTPError'
      summary: adds value to cell
swagger: "2.0"
