basePath: /api/v1
definitions:
  api.ValueResponse:
    properties:
      result:
        type: string
      value:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: iostapovychweb@gmail.com
  description: Educational Excel-like API
  title: ITSUXEL
  version: "1.0"
paths:
  /table/{sheet}:
    get:
      consumes:
      - application/json
      parameters:
      - description: sheet name
        in: path
        name: sheet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/api.ValueResponse'
            type: array
      summary: returns cell value
  /table/{sheet}/{cell}:
    get:
      consumes:
      - application/json
      parameters:
      - description: sheet name
        in: path
        name: sheet
        required: true
        type: string
      - description: cell address
        in: path
        name: cell
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.ValueResponse'
      summary: returns cell value
    post:
      consumes:
      - application/json
      description: Add a new pet to the store
      parameters:
      - description: sheet name
        in: path
        name: sheet
        required: true
        type: string
      - description: cell address
        in: path
        name: cell
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/api.ValueResponse'
      summary: adds value to cell
swagger: "2.0"
